### PR TITLE
Make comma-separated selectors work

### PR DESCRIPTION
**Pull request by dfcreative**
Just wrapped querySelector so to split selector by commas.

That’s for #16.

@lauriro @hayes

### CODE REVIEW

**Comment by dfcreative** [comment]
@lauriro I think there’s still need to rewrite the whole `findEl` thing to some really decent engine.

**Comment by lauriro** [comment]
http://sizzlejs.com/ could be option when full css selectors needed.

I think a little bit about what would be best solution for this project.

**Comment by dfcreative** [comment]
@lauriro there are also some others: [qwery](https://www.npmjs.com/package/qwery), [zest](https://github.com/chjj/zest), [nwmwatches](https://github.com/dperini/nwmatcher), [sel](https://www.npmjs.com/package/sel) and others with varying size/speed/usefulness.

Also take a look at [css-selector-parser](https://www.npmjs.com/package/css-selector-parser), might be just what you need.

**Comment by lauriro** [comment]
comma-separated selectors are supported from version 0.3

**Comment by dfcreative** [comment]
Great news

**Pull request closed without merging**
